name: Keep Streamlit Alive
on:
  schedule:
    - cron: '0 */10 * * *' # Runs every 10 hours
jobs:
  keep_awake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Make Empty Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Keeping the server awake!"
          git push
